# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DjiDroneMonitor' do
    use_frameworks!
    pod 'DJI-SDK-iOS', '~> 4.12'
    pod 'DJI-UXSDK-iOS', '~> 4.12'
    pod 'DJIWidget', '~> 1.6.2'

end
